# HMM (Hidden Markov Model)

In [1]:
import numpy as np

## 1. Initialisation

In [2]:
a_ij =  np.array([[1, 0, 0, 0], [0.2, 0.3, 0.1, 0.4], [0.2, 0.5, 0.2, 0.1],[0.7, 0.1, 0.1, 0.1]])
b_jk = np.array([[1, 0, 0, 0,0], [0, 0.3, 0.4, 0.1, 0.2],[0, 0.1, 0.1, 0.7, 0.1],[0, 0.5, 0.2 ,0.1, 0.2]])

## 2. Evaluation problem

In [3]:
def forward_eval(initial_state,a_ij,b_jk,X_seq=0):
    N = max(a_ij.shape[0],b_jk.shape[0]) #get the max value between the length of both matrixes, corresponds to the total number of j states named N 
    T = max(a_ij.shape[1],b_jk.shape[1])   #get the max value between the width of both matrixes, corresponds to the total time T of the sequence
    alpha = np.zeros((N,T)) #initialize alpha_j
    #alpha is of the form alpha[j][t] with j=0,..,N and t=0,...,T
    alpha[initial_state][0] = 1 #initialize initial_state to 1
    for t in range(1,T):
        for j in range(N):
            sum_prev = 0
            for k in range(N):
                sum_prev += alpha[k][t-1]*a_ij[k][j]
            k = X_seq[t-1]
            alpha[j][t]+= sum_prev * b_jk[j][k]
    return alpha

In [4]:
X_seq=[1,3,2,0]
initial_state = 1
alpha = forward_eval(initial_state,a_ij,b_jk,X_seq)
print(alpha)

[[0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 1.8218e-03]
 [1.0000e+00 9.0000e-02 5.2000e-03 5.1920e-03 0.0000e+00]
 [0.0000e+00 1.0000e-02 2.1700e-02 5.4300e-04 0.0000e+00]
 [0.0000e+00 2.0000e-01 5.7000e-03 9.6400e-04 0.0000e+00]]


#### Predict forward algorithm


In [5]:
#Je crois qu'on prends la case j=0 t=T
def predict(alpha,T=len(alpha)):
      return(alpha[0][T])

In [6]:
print("Probability of sequence ",[val for val in X_seq]," : ", predict(alpha))

Probability of sequence  [1, 3, 2, 0]  :  0.0018218000000000002


## 3. Decoding problem

In [7]:
#on reprend la matrice alpha construite precedemment et on prend l'index des plus hautes valeurs
def forward_decoding(alpha):
    path = []
    for col in alpha.T: #we iterate through all the columns of alpha
        index = np.argmax(col) #take the index of the highest value of the current column
        path.append(index) # add to path
    return path

In [8]:
forward_decoding(alpha)

[1, 3, 2, 1, 0]